openapi: 3.0.0
info:
  title: Smart Pet Feeder API
  description:
    TBA
  version: 3.0.0
servers:
  - url: http://127.0.0.1:8080/pet-feeder-api/v3
paths:
  /roomdata:
    get:
      summary: Returns a list of room data.
      operationId: controller.get_sensor_room_data
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SensorRoomData'
  /behavior:
    get:
      summary: Returns a list of behavior data that collect status which is the number and frequency value.
      operationId: controller.get_behavior_data
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BehaviorData'   
  /record:
    post:
      summary: Create a new resource
      operationId: controller.post_portion_data
      requestBody:
        description: Data to be sent in the request body
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                por:
                  type: integer
      responses:
        '201':
          description: Resource created successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /time:
    post:
      summary: Create a new resource
      operationId: controller.post_time_data
      requestBody:
        description: Data to be sent in the request body
        required: true
        content:
          application/json:
            schema:
                type: object
                properties:
                  days:
                    type: array
                    items:
                      type: string
                  time:
                    type: string
                  por:
                    type: integer

                
      responses:
        '201':
          description: Resource created successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error
                                

components:
  schemas:
    SensorRoomData:
      type: object
      properties:
        id:
          type: integer
        ts:
          type: string
        dis:
          type: number
          description: distance between sensor and object 
        por:
          type: integer
          description: food portion
    BehaviorData:
      type: object
      properties:
        id:
          type: integer
        ts:
          type: string
        status:
          type: integer
        freq:
          type: integer
    FeedingData:
      type: object
      properties:
        id:
          type: integer
        ts:
          type: string
        por:
          type: integer
          description: food portion