openapi: 3.0.0
info:
  title: Smart Pet Feeder API
  description:
    TBA
  version: 3.0.0
servers:
  - url: http://127.0.0.1:8080/pet-feeder-api/v3
paths:
  /roomdata:
    get:
      summary: Returns a list of room data.
      operationId: controller.get_sensor_room_data
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SensorRoomData'
  /data:
    get:
      summary: Return a list of room data combine with tank data.
      operationId: controller.get_room_and_tank_data
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoomAndTankData'

components:
  schemas:
    SensorRoomData:
      type: object
      properties:
        id:
          type: integer
        ts:
          type: string
        dis:
          type: number
          description: distance between sensor and object 
        por:
          type: integer
          description: food portion
    RoomAndTankData:
      type: object
      properties:
        room_temp: 
          type: number
          format: float
          description: temperature inside the room
        room_hum:
          type: number
          format: float
          description: humidity inside the room
        tank_temp:
          type: number
          format: float
          description: temperature inside the tank
        tank_hum:
          type: number
          format: float
          description: humidity inside the tank