openapi: 3.0.0
info:
  title: Smart Pet Feeder API
  description:
    TBA
  version: 3.0.0
servers:
  - url: http://127.0.0.1:8080/pet-feeder-api/v3
paths:
  /roomdata:
    get:
      summary: Returns a list of room data.
      operationId: controller.get_sensor_room_data
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SensorRoomData'
  /get-behavior-data:
    get:
      summary: Returns a list of behavior data that contains timestamp, frequency and status.
      operationId: controller.get_behavior_data
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BehaviorData'
  /get-meal-plan-data:
    get:
      summary: Get list of all meal plan data
      operationId: controller.get_meal_plan_data
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MealPlanData'
  /post-portion-data:
    post:
      summary: Receive the data on portion of pet food and insert into the feedingData database. 
      operationId: controller.post_portion_data
      requestBody:
        description: Data to be sent in the request body
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                por:
                  type: integer
      responses:
        '201':
          description: Resource created successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /post-meal-plan-data:
    post:
      summary: Recieve meal plan data and insert into mealPlan database
      operationId: controller.post_meal_plan_data
      requestBody:
        description: Data to be sent in the request body
        required: true
        content:
          application/json:
            schema:
                type: object
                properties:
                  days:
                    type: array
                    items:
                      type: string
                  schedule_id:
                      type: integer
                  time:
                    type: string
                  por:
                    type: integer
                  enable_status:
                    type: integer
      responses:
        '201':
          description: Resource created successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error
                                

components:
  schemas:
    SensorRoomData:
      type: object
      properties:
        id:
          type: integer
        ts:
          type: string
        dis:
          type: number
          description: distance between sensor and object 
        por:
          type: integer
          description: food portion
    BehaviorData:
      type: object
      properties:
        id:
          type: integer
        ts:
          type: string
        status:
          type: integer
        freq:
          type: integer
    FeedingData:
      type: object
      properties:
        id:
          type: integer
        ts:
          type: string
        por:
          type: integer
          description: food portion
    MealPlanData:
      type: object
      properties:
        schedule_id:
          type: integer
        days:
          type: array
          items:
            type: string
          description: List of days
        por:
          type: integer
          description: The 'portion' value
        time:
          type: string
          description: The 'time' value
        enable_status:
          type: integer      